### ISSUE TITLE
invalid requirements exception not caught

### ISSUE THREAD

**Issue by goern** [goern/thoth-dependency-monkey#11]
pip._vendor.packaging.requirements.InvalidRequirement is not catched by pypi-validator

##### Version
0.1.1

##### Steps To Reproduce
1. submit a validation request with 'pandas\nnumpy,,,1.11.0' as a specification

##### Current Result
raw_log of the Validation is null

##### Expected Result
raw_log should container at least 'Invalid requirement, parse error at "',,,1.11.''

##### Additional Information
```



DEBUG:/opt/app-root/src/validate:Thoth Dependency Monkey PyPI Validator v0.1.1 statring up...
  | DEBUG:/opt/app-root/src/validate:writing stack_specification to temparary file: /tmp/tdm-pypi-validation-1peo8jlq
  | Traceback (most recent call last):
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
  | req = REQUIREMENT.parseString(requirement_string)
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
  | raise exc
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
  | loc, tokens = self._parse( instring, 0 )
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
  | loc,tokens = self.parseImpl( instring, preloc, doActions )
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
  | loc, exprtokens = e._parse( instring, loc, doActions )
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
  | loc,tokens = self.parseImpl( instring, preloc, doActions )
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3164, in parseImpl
  | raise ParseException(instring, loc, self.errmsg, self)
  | pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 5), (line:1, col:6)
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 82, in __init__
  | req = Requirement(req)
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
  | requirement_string[e.loc:e.loc + 8]))
  | pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "',,,1.11.'"
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/opt/app-root/src/validate", line 75, in <module>
  | ['--annotate', '--verbose', '--output-file', '{}-requirements.txt'.format(f.name), f.name], catch_exceptions=False)
  | File "/usr/local/lib/python3.6/site-packages/click/testing.py", line 279, in invoke
  | prog_name=self.get_default_prog_name(cli), **extra)
  | File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
  | rv = self.invoke(ctx)
  | File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  | return ctx.invoke(self.callback, **ctx.params)
  | File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  | return callback(*args, **kwargs)
  | File "/usr/local/lib/python3.6/site-packages/piptools/scripts/compile.py", line 179, in cli
  | src_file, finder=repository.finder, session=repository.session, options=pip_options))
  | File "/usr/lib/python3.6/site-packages/pip/req/req_file.py", line 93, in parse_requirements
  | for req in req_iter:
  | File "/usr/lib/python3.6/site-packages/pip/req/req_file.py", line 158, in process_line
  | isolated=isolated, options=req_options, wheel_cache=wheel_cache
  | File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 235, in from_line
  | wheel_cache=wheel_cache, constraint=constraint)
  | File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 91, in __init__
  | "Invalid requirement: '%s'\n%s" % (req, add_msg))
  | pip.exceptions.InstallationError: Invalid requirement: 'numpy,,,1.11.0'
  | Traceback (most recent call last):
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 92, in __init__
  | req = REQUIREMENT.parseString(requirement_string)
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1617, in parseString
  | raise exc
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1607, in parseString
  | loc, tokens = self._parse( instring, 0 )
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
  | loc,tokens = self.parseImpl( instring, preloc, doActions )
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3376, in parseImpl
  | loc, exprtokens = e._parse( instring, loc, doActions )
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
  | loc,tokens = self.parseImpl( instring, preloc, doActions )
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/pyparsing.py", line 3164, in parseImpl
  | raise ParseException(instring, loc, self.errmsg, self)
  | pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 5), (line:1, col:6)
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 82, in __init__
  | req = Requirement(req)
  | File "/usr/lib/python3.6/site-packages/pip/_vendor/packaging/requirements.py", line 96, in __init__
  | requirement_string[e.loc:e.loc + 8]))
  | pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "',,,1.11.'"
 


```

**Comment by ace2107** [comment]
This will be solved as part of the code added by me in validation_dao where if there is an invalid request error is raised and printed by logger
